### ISSUE TITLE
Setup Recipe-App Kanban Board

### ISSUE THREAD

**Issue by Miliyonayalew** [Miliyonayalew/recipe-app#12]
# In this milestone we @IngDavidTM  and @Miliyonayalew setup the kanban board
- We are a group of two members
- Here is the link to our Kanban board setup [Kanban Board](https://github.com/Miliyonayalew/recipe-app/projects/1)

**Comment by julie-ify** [comment]
Hi @Miliyonayalew and @IngDavidTM,

## Highlights!
- Descriptive pull request ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
